language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_install:
  - echo 'test'
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh


script:
  # - docker build -t cisaia/apisimplon:latest . 
  - HEROKU_API_KEY=$HEROKU_PASSWORD heroku container:login
  - HEROKU_API_KEY=$HEROKU_PASSWORD heroku container:push web --app $HEROKU_APP_NAME
  - HEROKU_API_KEY=$HEROKU_PASSWORD heroku container:release web --app $HEROKU_APP_NAME


# deploy:
#   provider: script
#   script: 
#     # docker push cisaia/apisimplon;

#     # docker push registry.heroku.com/$HEROKU_APP_NAME/web;
#     heroku container:push web --app $HEROKU_APP_NAME
#     heroku container:release web --app $HEROKU_APP_NAME
#   on:
#     branch: master
